os: osx
osx_image: xcode8
language: node_js
cache:
  npm: false
node_js:
- node
before_script:
- npm install -g grunt-cli npm
- export CSC_IDENTITY_AUTO_DISCOVERY=false
- npm run publish-osx
env:
  global:
    secure: aWT7WWFJ1+uxXYUv1hJzoMxMZ0svclXB6oSBxuBJLGzxnek/HfrJ+kTSIMI1mT6UOISiszisTh+ydcwosMcULVp6xUO8hDcDxvYlhgv6OBp4frWEPHcpBZj+3EVev85+LN5sqjDdXaoNn3F6vy7rzjvec8PLytOhjcOcI0MXQGUiiWAtsh4qdmpGAVwUJ7UpI9SZuCixmryUoDuiL9A5jaw6o6gHvXnSC8uYaHy61BCA3VeEtGh0XavHSo9p2Il5y03RXGlF+3B0zsCNoG/t5NU6uOmnvCEYjR5qIEx5CxyDtQWYihPwGk2zT+Nsgz+Iy0yA3+LU7dj3PRf8nxInrOZSjWtBdzVKXjSgOoF7DumhNmqSISJrNNz+3rEPSGc63TZwDo0F2/wV1rcShrEBlSFJjACFr7pbk9eaFXw7q92UVTsBtTXI/iMas9VG0kOsHH0i8F2EJ3Tad5cyjM1En7yeEGETXSxGQkrk6KGEdSzv6mv1lQ5AsPJ196ljIM1t5IXeBVNFv5E4CvAwdsOnN/yEwcJNeT7ia9l0GrzI7ubRzAx6wxc0ouwOy7HLEiD29VjbSDp2z3au0Lixa1mWhE4F1FmcA02XbdTFMt1HdNsz5BoFaSAVoc6WJnQWtT4fVRxF8LjOvecGxjr5q1N9y4djbgLjE3HvEtJ39bWfyz4=
