os: osx
osx_image: xcode8
language: node_js
cache:
  npm: false
node_js:
- node
before_script:
- npm install -g grunt-cli npm
- export CSC_IDENTITY_AUTO_DISCOVERY=false
- npm run publish-osx
env:
  global:
    secure: UZPudR8+F9S/cxUH+v1mWUGqPUWKprlkkza015n/jpUB3RFi1kZjyKNcMSAUeO6YnS3/D6zb70iPdKcQbdprRfm5KiccMKPCzNwqwUUKd/sRecDLkfp00yn5FgC88sLdkOlsWV4i8okL4aJpsb6nsjFgGC7sWGSET5YuXjXprIrn1KbzfGTY1rFR/HBu0IDyng33YiM9SGCX/6fkwU5+uQzBrYt4pN/B6RCumkJFNDWU72CXx++doHVA4heG0eSdIlVK+j9V4yO4LTdsNG6udYR9QHuypNdN24A+LWevybDZ9TOWzBVZd+wDd9N5raxthQA+jOKo18xLJKuNDtyxM7jo0IOs/esaoDr7Bf+XntDR9P0+jBeNuPIARiKxB+r4GIGf+5leO0+SxIC1YFaVLODxwpB1mrk0VrLllEaxN3y1k6Q2Bi3Krz6wWYD5uqKNVLF/6eYmtQgLOaFCycCvgoAWBqrHFcjKX2vIUqTZrsA2RvwddEj1iVLxm2XWI5DwPXiqR4nf36nde5J7rr2+M6zONQtVMc4VKHMJZ0BaNMznYTScEhl92xJRGx1dh3IZDQEu/iHki86Nz9a9H7XdFFg6p/7R16O5dl8Qxq6iONno5QXLvisIulqbgitSYb/1arf84+GPVFxKLsFo6Q5iOurbJPEYSGSVIkf8WyTqm9g=
